:Author: Douglas Navarro e Renan Yuri Lino
:Email: contato@codedecay.com.br
:Date: 24/12/2016
:Revision: 2.1
:License: Apache 2.0

= Bibliotecas de Figuras XBMP

As figuras deste diretório foram, em sua maioria, extraídas de stickers do aplicativo Telegram e convertidas para o formato XBM com o auxílio do GIMP.
Cada um dos arquivos está acompanhado do seu respectivo .jpg para visualização prévia.
Todos os arquivos são compatíveis com a biblioteca U8G2 para controle de displays.

== Como usar?

1. Copie o arquivo .h da figura desejada para a pasta do seu sketch.
2. Faça o include adequado no sketch.
3. Use o método drawXBMP() para desenhar a figura no display.

== Como converter minhas próprias figuras?

1. Abrir a imagem com o editor GIMP
2. Image > Autocrop Image
3. Image > Scale Image (max. 128 x 64)
4. Image > Mode > Indexed > 1 bit
5. File > Export as… > Salvar como .xbm
6. Abrir o arquivo XBM com um editor de texto (bloco de notas, Atom, Notepad++)
7. Adicionar os modificadores const e U8X8_PROGMEM
8. Salvar como .h

=== Licença
Os códigos das figuras estão disponíveis sob a licença {License}.

=== Contribuindo
Para contribuir com este projeto, entre em contato com {Author} <{Email}>

=== Help
This document is written in the _AsciiDoc_ format, a markup language to describe documents.
If you need help you can search the http://www.methods.co.nz/asciidoc[AsciiDoc homepage]
or consult the http://powerman.name/doc/asciidoc[AsciiDoc cheatsheet]
